blank_issues_enabled: true
contact_links:
  - name: Support Request
    url: https://github.com/ks6088ts/.github/issues
    about: Create an issue for support request or question relating to this repository
